/**
 * Lazy loader + search for the full Tabler outline icon set.
 *
 * The dataset (`tabler-icons.json`, ~5000 icons, generated by
 * `scripts/gen-tabler.mjs`) is loaded via dynamic import the first time the
 * import dialog opens, so it lands in its own bundle chunk and never affects
 * the initial editor load.
 */

/** One icon: `n`ame, search `t`ags, visible path `p`aths. */
export type TablerIconEntry = { n: string; t: string[]; p: string[] };

let cache: TablerIconEntry[] | null = null;
let loading: Promise<TablerIconEntry[]> | null = null;

/** Load (and memoise) the icon dataset. Safe to call repeatedly. */
export function loadTablerIcons(): Promise<TablerIconEntry[]> {
  if (cache) return Promise.resolve(cache);
  if (!loading) {
    loading = import("./tabler-icons.json").then((mod) => {
      cache = ((mod as { default?: unknown }).default ?? mod) as TablerIconEntry[];
      return cache;
    });
  }
  return loading;
}

/**
 * Filter icons by a free-text query against name + tags. Empty query returns
 * the head of the list. Name matches rank above tag-only matches; results are
 * capped so rendering thousands of previews never stalls the dialog.
 */
export function searchTablerIcons(
  icons: TablerIconEntry[],
  query: string,
  limit = 200
): TablerIconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return icons.slice(0, limit);

  const nameHits: TablerIconEntry[] = [];
  const tagHits: TablerIconEntry[] = [];
  for (const icon of icons) {
    if (icon.n.includes(q)) {
      nameHits.push(icon);
    } else if (icon.t.some((tag) => tag.toLowerCase().includes(q))) {
      tagHits.push(icon);
    }
    if (nameHits.length >= limit) break;
  }
  return [...nameHits, ...tagHits].slice(0, limit);
}
